# Generated by Django 5.0.6 on 2024-06-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('1', 'Talaba'), ('2', 'Hodim'), ('3', "O'qituvchi")], default='1', max_length=20, null=True, verbose_name='Type'),
        ),
    ]
