# Generated by Django 5.0.6 on 2024-07-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_logentry_browser_name_logentry_device_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='location_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
