# Generated by Django 5.0.6 on 2024-07-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_logentry_location_lat_logentry_location_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='location_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
