# Generated by Django 5.0.6 on 2024-07-02 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_alter_logentry_location_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logentry',
            old_name='local_ip',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='location_lon',
        ),
    ]
