# Generated by Django 5.0.6 on 2024-07-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=15)),
                ('mac_address', models.CharField(max_length=17)),
                ('manufacturer', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Tasdiqlangan', 'Tasdiqlangan'), ('Tasdiqlanmagan', 'Tasdiqlanmagan'), ("Ta'qiqlangan", "Ta'qiqlangan")], max_length=20)),
            ],
        ),
    ]
