# Generated by Django 5.0.6 on 2024-07-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='device_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='user_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
